### ISSUE TITLE
The project must be updated to work with OIDC 

### ISSUE THREAD

**Issue by nnats** [auth0-community/auth0-servicestack-samples#10]
Steps to reproduce the error:

- Turn on OIDC conformant toggle.
- Run the seed project.
Expected result: The log in works.
Result: The Logs from Auth0 show this message: " Password login is disabled for clients using externally
             hosted login pages with oidc_conformant flag set."

![image](https://cloud.githubusercontent.com/assets/20141842/25786598/86c50a6a-336e-11e7-9ca4-d6c685ef1379.png)

**Comment by JimCMorrison** [comment]
After reviewing as a team we’ve decided to deprecate this repository 
in favor of focusing on more actively leveraged projects. We will be 
closing all open issues and pull requests, as a result of these changes.  
If you need any further help from our team you can reach out at 
[Community.Auth0.com](https://community.auth0.com/) -- Thank you for your contributions.
