### ISSUE TITLE
State parameter missing on callback

### ISSUE THREAD

**Issue by rafanog** [auth0-community/auth0-servicestack-samples#15]
The state parameter is missing when the user logs in with full credentials, the resultant callback does contain the mentioned parameter when the "last logged in with " option is selected:
![image](https://user-images.githubusercontent.com/15782359/37991183-832f1de8-31d6-11e8-9f85-9e1c9dccf0d5.png)

**Comment by JimCMorrison** [comment]
After reviewing as a team we’ve decided to deprecate this repository 
in favor of focusing on more actively leveraged projects. We will be 
closing all open issues and pull requests, as a result of these changes.  
If you need any further help from our team you can reach out at 
[Community.Auth0.com](https://community.auth0.com/) -- Thank you for your contributions.
